{{- define "cloudConf" }}
{{- printf `[Global]
auth-url = %s
username = %s
password = %s
domain-id = %s
tenant-id = %s
region = %s
` .Values.openstack.authURL .Values.openstack.userName .Values.openstack.password .Values.openstack.domainID .Values.openstack.projectID .Values.openstack.region | b64enc }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  annotations:
    description: Cloud config for CephFS CSI driver
  name: cloudconfig
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  cloud.conf: {{ template "cloudConf" . }}
