apiVersion: v1
kind: ServiceAccount
metadata:
  name: manila-provisioner
  namespace: {{ .Release.Namespace }}

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manila-provisioner
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: manila-provisioner
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: system:csi-external-provisioner
  apiGroup: rbac.authorization.k8s.io

---
# manila provisioner needs to manage secrets and endpoints in its namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manila-provisioner-edit
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: manila-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
