apiVersion: v1
kind: Secret
metadata:
  annotations:
    description: Manila provisioner credentials to access to the OpenStack API
  name: manila-provisioner-os-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  os-authURL:   {{ .Values.openstack.authURL   | b64enc }}
  os-domainID:  {{ .Values.openstack.domainID  | b64enc }}
  os-password:  {{ .Values.openstack.password  | b64enc }}
  os-projectID: {{ .Values.openstack.projectID | b64enc }}
  os-region:    {{ .Values.openstack.region    | b64enc }}
  os-userName:  {{ .Values.openstack.userName  | b64enc }}
