apiVersion: v1
kind: Secret
metadata:
  annotations:
    description: "CephFS credentials to backup the CephFS PVs using S3."
  name: cephfs-backup-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  cephfs-backup-s3-access-key:       {{ .Values.s3.cephfsBackupS3AccessKey        | b64enc }}
  cephfs-backup-s3-secret-key:       {{ .Values.s3.cephfsBackupS3SecretKey        | b64enc }}
  cephfs-backup-password:            {{ .Values.s3.cephfsBackupPassword           | b64enc }}
  cephfs-backup-registry-repository: {{ .Values.s3.cephfsBackupRegistryRepository | b64enc }}
