apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.backup.serviceAccountName }}
  namespace: {{ .Release.Namespace }}

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cephfs-backup-job
subjects:
  - kind: ServiceAccount
    name: {{ .Values.backup.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  # Use csi-external-attacher to patch pvs when annotating them
  name: system:csi-external-attacher
  apiGroup: rbac.authorization.k8s.io

---
# It needs to read the secrets of the namespace od the driver
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-secrets-global
subjects:
  - kind: ServiceAccount
    name: {{ .Values.backup.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-reader

---
# It needs to list pods locally as downward API does not work
# as it does not recognize the labels.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pods-reader
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods-locally
subjects:
  - kind: ServiceAccount
    name: {{ .Values.backup.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pods-reader
